### ISSUE TITLE
Problems parsing sentence in para 4.1.4

### ISSUE THREAD

**Issue by seanturner** [rtcweb-wg/security#9]
In Adam's AD review:

    I can't parse this sentence. Consider reworking.    

    Even if calls are only possible from HTTPS [RFC2818] sites, if the
    site embeds active content (e.g., JavaScript) that is fetched over
    HTTP or from an untrusted site, because that JavaScript is executed
    in the security context of the page [finer-grained].

**Comment by ekr** [comment]
@seanturner do you have a proposal here?

**Comment by seanturner** [comment]
@ekr how about the following knowing that you're trying to bridge the previous that talks about HTTP origins:

    It is also dangerous to allow WebRTC functionality from HTTPS [RFC2818]
    origins that embed mixed content because if the site embeds active content
    (e.g., JavaScript) that is fetched over HTTP or from an untrusted site that
    JavaScript is executed in the security context of the page [finer-grained].

Note this would replace the 1st two sentences in the last para of §4.1.4 copied here for convenience:

    Even if calls are only possible from HTTPS [RFC2818] sites, if the
    site embeds active content (e.g., JavaScript) that is fetched over
    HTTP or from an untrusted site, because that JavaScript is executed
    in the security context of the page [finer-grained].  Thus, it is
    also dangerous to allow WebRTC functionality from HTTPS origins that
    embed mixed content.

**Comment by martinthomson** [comment]
Has this been overtaken by events?  I mean, while it might have been the case that some browsers permitted the use of active mixed content when this was originally written, I don't believe that any currently do.  Could the text be removed?

**Comment by seanturner** [comment]
I guess it could, but this is the section on "Security Properties of the Calling Page" so maybe for posterity we make this tweak, but also add to the end of the paragraph:

    Note: the issue of active mixed content was an issue, but is now implemented by browsers.

And, (not having read the link entirely) we also informatively point to this [Mixed Content](https://w3c.github.io/webappsec-mixed-content/) W3C draft?
